name: Maven CI/CD

on:
  push:
    branches:
      - main

jobs:
  CI_Test_And_Build:
    runs-on: ubuntu-latest

    steps:
      - name: Hacemos Checkout del repo de Git
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Test project with Maven
        # Directorio de trabajo para los comandos de Maven
        working-directory: ./mvn-hello-world
        run: mvn -B test

      - name: Build project with Maven
        # Directorio de trabajo para los comandos de Maven
        working-directory: ./mvn-hello-world
        run: mvn -B package

      - name: Get Version from POM.xml
        uses: entimaniac/read-pom-version-action@1.0.0
        id: getVersion

      - name: Copy generated .war to staging
        run: mkdir staging && cp ./mvn-hello-world/target/*.war staging

      - name: Upload generated .war to Artifact
        uses: actions/upload-artifact@v3
        with:
          name: mvn-hello-world-${{ steps.getVersion.outputs.version }}.zip
          path: staging