name: Maven CI/CD

on:
  push:
    branches:
      - main

jobs:
  CI_Test_And_Build:
    runs-on: ubuntu-latest

    steps:
      - name: Hacemos Checkout del repo de Git
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Test project with Maven
        working-directory: "Curso-Docker-Tema-9/mvn-hello-world"
        run: mvn -B test

      - name: Build project with Maven
        working-directory: "Curso-Docker-Tema-9/mvn-hello-world"
        run: mvn -B package

