name: Maven CI/CD

on:
  push:
    branches:
      - development

jobs:
  CI_Test_And_Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Ejecutar tests con Maven
        working-directory: Curso-Docker-Tema-9
        run: mvn -B test

      - name: Construir proyecto con Maven
        working-directory: Curso-Docker-Tema-9
        run: mvn -B package

      - name: Obtener versión desde pom.xml
        uses: entimaniac/read-pom-version-action@1.0.0
        id: getVersion
        with:
          path: Curso-Docker-Tema-9

      - name: Copiar el archivo .war a staging
        run: mkdir staging && cp Curso-Docker-Tema-9/target/*.war staging

      - name: Subir el .war generado como artefacto
        uses: actions/upload-artifact@v3
        with:
          name: mvn-hello-world-${{ steps.getVersion.outputs.version }}.zip
          path: staging
